-- H2 版本：審計日誌表

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    tenant_id VARCHAR(100) NOT NULL,
    performed_by VARCHAR(100),
    policy_module VARCHAR(200),
    policy_function VARCHAR(200),
    policy_id VARCHAR(100),
    from_version BIGINT,
    to_version BIGINT,
    execution_time_ms BIGINT,
    success BOOLEAN,
    reason VARCHAR(500),
    notes CLOB,
    client_ip VARCHAR(50),
    user_agent VARCHAR(500)
);

CREATE INDEX idx_audit_tenant ON audit_logs (tenant_id);
CREATE INDEX idx_audit_event_type ON audit_logs (event_type);
CREATE INDEX idx_audit_timestamp ON audit_logs (timestamp);
CREATE INDEX idx_audit_policy ON audit_logs (policy_module, policy_function);
