-- H2 版本：策略版本表

CREATE TABLE policy_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id VARCHAR(100) NOT NULL,
    version BIGINT NOT NULL,
    module_name VARCHAR(200) NOT NULL,
    function_name VARCHAR(200) NOT NULL,
    content CLOB NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    created_by VARCHAR(100),
    notes CLOB,
    CONSTRAINT uk_policy_version UNIQUE (policy_id, version)
);

CREATE INDEX idx_policy_id_active ON policy_versions (policy_id, active);
CREATE INDEX idx_policy_id_version ON policy_versions (policy_id, version);
