-- H2 版本：Workflow Events 表

CREATE TABLE workflow_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id UUID NOT NULL,
    sequence BIGINT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    payload CLOB NOT NULL,
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    idempotency_key VARCHAR(255),
    CONSTRAINT uq_workflow_events_sequence UNIQUE (workflow_id, sequence),
    CONSTRAINT uq_workflow_events_idem UNIQUE (workflow_id, idempotency_key)
);

CREATE INDEX idx_workflow_events_occurred ON workflow_events (occurred_at);
