-- 为 workflow_events 增加自增序列列，保持与 PostgreSQL 结构一致
ALTER TABLE workflow_events
ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- 创建索引提升按 seq 扫描性能
CREATE INDEX idx_workflow_events_seq ON workflow_events(seq);
