-- Phase 3.7: 创建异常响应动作队列表 - Outbox 模式
-- 作者: Claude Code
-- 日期: 2025-11-11
-- 目的: 解耦异常检测与响应执行，支持异步动作处理
-- H2 兼容版本：BIGSERIAL→IDENTITY, JSONB→JSON, TEXT→VARCHAR, 移除 COMMENT ON

CREATE TABLE anomaly_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- H2: BIGSERIAL→IDENTITY
    anomaly_id BIGINT NOT NULL,
    action_type VARCHAR(32) NOT NULL,
    status VARCHAR(16) DEFAULT 'PENDING' NOT NULL,
    payload JSON,  -- H2: JSONB→JSON
    error_message VARCHAR(10000),  -- H2: TEXT→VARCHAR(10000)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    started_at TIMESTAMP,
    completed_at TIMESTAMP
);

-- 外键：关联异常报告，级联删除
ALTER TABLE anomaly_actions
ADD CONSTRAINT fk_anomaly_actions_anomaly_id
FOREIGN KEY (anomaly_id) REFERENCES anomaly_reports(id)
ON DELETE CASCADE;

-- 部分索引：H2 支持 WHERE 条件的索引
CREATE INDEX idx_anomaly_actions_status_created
ON anomaly_actions(status, created_at);
-- WHERE status IN ('PENDING', 'RUNNING'); -- H2 部分支持，但为兼容性省略

-- 普通索引：按异常 ID 查询该异常的所有动作历史
CREATE INDEX idx_anomaly_actions_anomaly_id
ON anomaly_actions(anomaly_id);

-- H2 不支持 COMMENT ON，使用内联注释代替
-- anomaly_actions 表：异常响应动作队列表，采用 outbox 模式解耦检测与执行
-- action_type：动作类型：VERIFY_REPLAY, AUTO_ROLLBACK
-- status：动作状态：PENDING, RUNNING, DONE, FAILED
-- payload：动作参数 JSON，如 {workflowId, targetVersion}
-- error_message：执行失败时的错误信息
-- created_at：动作创建时间（提交到队列）
-- started_at：开始执行时间
-- completed_at：完成时间（成功或失败）
