version: '3.8'

services:
  postgres:
    image: docker.io/bitnami/postgresql:18
    container_name: policy-api-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: aster_policy
    volumes:
      - postgres-data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  policy-api:
    image: aster/policy-api:test
    container_name: policy-api
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/aster_policy
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://postgres:5432/aster_policy
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_FLYWAY_MIGRATE_AT_START: "true"
    depends_on:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/q/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  postgres-data:
